//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeSemester2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int ModuleId { get; set; }
        public string MacAddress { get; set; }
        public string IssueDate { get; set; }
        public string StudentId { get; set; }
    
        public virtual User User { get; set; }
    }
}
